[workspace]
resolver = "2"
members = [
    "ft_func_composed",
    "worker",
    "download",
    "list_files",
    "file_transfer_func_api",
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
